swagger: '2.0'
info:
  version: '1.0.0'
  title: 'node-api-rest'
  description: 'API Rest created with Express'
host: localhost
basePath: '/api'
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      tags:
        - Users
      summary: "Get all users"
      responses:
        200:
          description: A JSON array of users
        404:
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  /active-users:
    get:
      tags:
        - ActiveUsers
      summary: "Get all active users ordered alphabetically"
      responses:
        200:
          description: A JSON array of users
        404:
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error